baseURL = "https://moonshotlife.netlify.app/"
title = "Moonshot Life"
theme = "minimal"
languageCode = "ja"
hasCJKLanguage = true
summaryLength = 70
enableEmoji = true
enableGitInfo = true
pluralizeListTitles = false
disqusShortname = "moonshotlife"
googleAnalytics = "UA-167776351-1"
# Code pen
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Moonshot Life"
description = ""
copyright = "Copyright © 2020, Moonshot Life; all rights reserved."
githubUsername = "#"
accent = "#808080"
showBorder = true
backgroundColor = "#fcfcfc"
font = "Times New Roman"
highlight = true
highlightStyle = "ocean"
highlightLanguages = ["bash", "cpp", "python", "go"]
disableComments = false

[[menu.main]]
url = "/"
name = "Home"
weight = 1

[[menu.main]]
url = "/about/"
name = "About"
weight = 2

[[menu.main]]
url = "/money/"
name = "Money"
weight = 3

[[menu.main]]
url = "/tech/"
name = "Tech"
weight = 4

[[menu.main]]
url = "/misc/"
name = "Misc"
weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

# [[menu.icon]]
# url = "https://github.com/username/"
# name = "github"
# weight = 2

# [[menu.icon]]
# url = "https://twitter.com/username/"
# name = "twitter"
# weight = 3
