#+HUGO_BASE_DIR: ~/ws/hugo/moonshotlife
#+HUGO_AUTO_SET_LASTMOD: t
#+STARTUP: logdone
#+TAGS: @Money(m) @Tech(t) @Misc(o)
#+TAGS: emacs options forex stocks strategy trading investing market retirement

* About                                                              :@About:
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: .
  :EXPORT_FILE_NAME: about
  :END:
  「経済的自立を達成し会社員という束縛からの開放」というMoonshotな夢を追いかけるblogです。

* Misc                                                                :@Misc:
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: misc
  :END:

** アーリーリタイア、セミリタイア、FIRE                          :retirement:
   :PROPERTIES:
   :EXPORT_FILE_NAME: surfing-early-retirement-blogs
   :END:
    
  目標は2、3年後に会社員をやめて個人事業主としてトレーディングbotやシステムの開発に没頭したい。週末に40代、50代でリタイアした人のブログを眺めてみた。リタイアすると健康保険がびっくりするぐらい高くなるとか、国民年金免除の方がいいのでは、などという有益な情報が得られたが、自分と似たような属性の人がいなくてちょっとがっかり。リタイア時は当方、

   - 5人家族
   - 東京都内(目黒区)に在住(子供の通学関係で妻が強く希望するだろうから)
   - 子供の学費が年数百万かかるのが8-10年続きそう
   - 妻は専業主婦
   - 借金ないけど持ち家もない
   - 資産の半分以上は個別株なのだが配当がほとんどない(ので配当生活は無理)

のようなリタイアするにはかなり不利な属性である。やはり会社を辞める前に住宅ローン組んで家を買ったほうがいいんだろうなぁ。悩ましいところである。

* Tech                                                                :@Tech:
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: tech
  :END:

** Hugo and Ox-Hugo                                                   :emacs:
   :PROPERTIES:
   :EXPORT_FILE_NAME: hugo-and-ox-hugo
   :END:
   blogを書こうと思ってはてなブログとかにも登録したけど、いざ書こうと思うとサイトに行ってログインして、、となってめんどくさくてやはり挫折。でもやはり思ったことをbraindumpするのはいろいろ役に立つのでなんとかしたいと思い、HugoとOx-Hugoでまた挑戦してみることにした。

* Money                                                              :@Money:
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: money
  :END:

** DONE Probability of Profit                                       :options:
   CLOSED: [2020-05-28 Thu 23:08]
   :PROPERTIES:
   :EXPORT_FILE_NAME: probability-of-profit
   :END:

   オプションはexpiration dateのときにIMTになる確率(Probability of Profit, or POP)を統計学的に求めることができるので、OTMのオプションを売ることにより50%の確率より有利な確率で利益を得ることが期待できる。ただしOTMなので確率が上がるに従って利益幅は小さくなる。大数の法則(The law of large numbers)より、高確率のトレードを数多くこなすことにより確率50%前後しかない株式(極論すると上がるか下がるか)よりリスクを抑えて利益を上げることが期待できる。

   と、ここまではTastytradeやOptions Alphaの受け売りであるが、実際の確率については根拠をあげて詳しく説明してくれるページがあまり見つからなかった。deltaがPOPであるとか、spreadのときは1 - credit (strike widthが$1のとき)であるとか、さらっと書いてあるだけ。deltaで近似できることについては、Tastytradeの[[https://www.tastytrade.com/tt/shows/the-skinny-on-options-math/episodes/probability-of-profit-08-06-2015][このセグメント]]が数式を交えて説明していてなるほどと納得した。

   vertical spreadのPOPについては、自分で考えてみた。Strike width wのcreditがcのとき、POP pは

   - max profit = c
   - max loss = w - c
 
   であるので、

   \[c * p - (w - c) * (1 - p) >= 0\]

   のpを求めればいい。数式を解いていくと、

   \[c * p - (w - w * p - c + c * p) >= 0\]
   \[c * p - w + w * p + c - c * p >= 0\]
   \[p * w - w + c >= 0\]
   \[p >= (w - c) / w\]
   となる。合ってるかな〜。

   でも、オプション価格(premium)って絶えず変わるから、確率ってあくまでopen時の確率に過ぎない。だからopen時にPOPが80%あったとしても、credit価格の推移をちゃんとチェックし続けないとってことだ。


** DONE 売買プランと戦術                                           :strategy:
   CLOSED: [2020-05-13 Wed 00:25]
   :PROPERTIES:
   :EXPORT_FILE_NAME: initial-trading-plan-and-strategy
   :END:

   やはり先週軽い気持ちで280Pを買って$265.65すってしまったのでまた情報収集ばかりに時間をかけてしまっている。悪い癖だ。ギャンブルするにせよ、ロングは上限決めたほうがいいな。$50とか。

   オプションに魅力を感じたのは50%以上の勝つ確率がある数学的手法が使えるからと、小さなサイズで回数を多くトレードすることにより大数の法則を利用することが可能なトレーディングだからだ。てことは、やはりストレス発散のロングギャンブルは別として、トレードはちゃんと戦術を勉強してからにしたい。

   とはいっても、戦術は当面クレジットスプレッドから始めて経験を積みながら戦術の幅を広げていくことかなと思う。売買プランについては、とりあえずたたき台としてtastytradeで提示してたやつを使わせてもらおうと思う。

   - 1 SDでショートすればprobabilityは84%
   - ショートならIV Rankが50以上
   - Limit orderを使う。marketを追うのではなく寄ってくるのを待つ
   - Liquidityを確保するためにVolumeは1M以上
   - 30-50DTEが理想
   - 50% max profitをターゲットにclose
   - 少なくともexpirationの1週間前にはclose

** DONE オプショントレード修行前夜                                  :options:
   CLOSED: [2020-05-08 Fri 01:23]
   :PROPERTIES:
   :EXPORT_FILE_NAME: the-eve-of-options-trading-training
   :END:

   ここもう何ヶ月かずっと情報収集ばかりしていて実際のオプショントレードは始めていなかった。コロナでずっと自宅にいることもあり、精神的にも煮詰まってきて月曜日にあまり後先考えずにSPY May 8 280Pロングを買ってしまった。$265也。損失が限定されている安心感からか何気に買ってしまったが、案の定現状価値がほぼなくなっており、明日はOTM確定でまるまる損することになるだろう。

   しかし、やはり実際にトレードしてみるとその後のモチベーションが全然違う。NatenbergのOption Volatility & Pricingは読むとすぐに眠くなりなかなか進まなかったが、RedditのOptions subとともにがんばって読み、またTastytradeのYouTube動画を今週は見まくった。願わくばlossが1/10ぐらいだったらもっとよかったのだが。

   IBKRも今週久しぶりにいろいろ試行錯誤してみた。Idle cashへのinterest rateが1%違うのでProアカウントにしていたが、rateが0%な今Liteにスイッチしようか迷った。Liteにすればstreaming market dataがただで使えるが、Proだと$14.5/monthのfeeがとられる。結構大きい。しかし、Liteでオプショントレードするのになにかcatchがあるのではないかという懸念から、結局Proのままで$14.5のBundle market dataをsubscribeした。毎月feeを取られることが逆にいいモチベーションになってくれることを期待する。

   実際のトレード戦略についてはTaastytradeが大変参考になった。これについては改めて記事にしたい。さて、明日(もう今日か)価値が消滅するオプションをしっかり見て、今後軽率なトレードをしないように心に刻み込もう。

** DONE オプショントレード普及協会                                  :options:
   CLOSED: [2020-05-02 Sat 00:47]
   :PROPERTIES:
   :EXPORT_FILE_NAME: option-trade-fukyu-kyokai
   :END:

   オプショントレード普及協会のYouTube動画をいくつか観た。月末月始めに日経VIが20以下になったら機械的にプットロングというのは面白かったが、ボラがまだ高い今はまだ無理な戦略か。今ぐらいの中途半端なボラのときは小銭稼ぎのコールショートの方がよさげだが、Naked売りは精神的に無理なのでコールクレジットスプレッドになるのか。プットデビットスプレッドはコスト的に妥当なのかいまだよくわからん。オプションチェインもろくに見てないので、時間を割いてまずはそこらへんの経験を積まないといけないな。

   
** DONE Junk bond strategy                                         :strategy:
   CLOSED: [2020-05-02 Sat 00:47]
   :PROPERTIES:
   :EXPORT_FILE_NAME: junk-bond-strategy
   :END:
   気になるニュース。ドイツが感染者数再び増加したとのこと。ロシアも100,000人を超えたらしい。USは100万人超えてるけど。ロシアはともかく、経済活動再開するとまた感染者数が増加というジレンマはワクチンなど特効薬が登場するまで続くだろう。コロナの治療薬Remdesivirの効果が期待できるとニュースで報道していたが、国際的には賛否両論あるらしい。

   Earnings reportに伴い事業縮小や解雇のニュースが連日報道される。Boeing, Uber, Lyftなど。また、200,000人以上のH1B workerが6月に職を失うかもしれないというニュースもあった。H1Bの3/4はTech業界らしい。非常事態宣言が長引けばこのようなニュースは益々増えるだろう。

   このようなニュースを聞く限りでは、株価がこれ以上上がることは難しいのではないかと思うのだが、一方Fedが低金利政策および量的緩和政策を実行しており、無制限に国債、社債、ジャンク債までも買い入れるらしい。この資金が株式市場に流入して株価を支えているのだろうか。今仮に暴落しているジャンク債があったとしたら、Fedが買い入れしてくれるのを期待して買う戦術は現実的だろうか。

   為替はとりあえず106円半ばで踏みとどまったっぽい。現在106.69円。今は為替と株式は連動してないな多分。

** DONE After all of the earnings
   CLOSED: [2020-04-28 Tue 23:30]
   :PROPERTIES:
   :EXPORT_FILE_NAME: after-all-of-the-earnings
   :END:
   仕事が忙しくてこのところマーケットを見てる時間がないがやる気はある。コロナのせいで周りで解雇の話を聞くと、会社に頼らず生きていく術を見つけないといけないと思う。

   今日はSPYが$291まで上昇したが、最後は$285.77でcloseした。現在まではQ1 earnings reportが壊滅的ではないので株価は比較的安定しているが、3ヶ月後のQ2はQ1と比較するとかなりのダメージになるだろう。そういう観点からは、Q2 earnings reportの時期をターゲットにしてshortすればいいような気がするが、短期的にはまだ上昇しそうなのでどこで仕掛けるか予めちゃんと計画を立てておかないと。

   気になるのはUSDJPYである。22日からずっと下降しており、今や106.55円である。日米の金利差が縮まったことでドル安(円高)になるのはある意味理にかなっているのだが、３月にコロナの影響でドル建ての負債返済のためにドル買いが起きてドル高になったので素直にこのまま円高傾向になるのかは読めない。

** DONE Braindump for the next strategy                            :strategy:
   CLOSED: [2020-04-19 Sun 23:02]
   :PROPERTIES:
   :EXPORT_FILE_NAME: braindump-for-the-next-strategy
   :END:

  とりあえず今後の投資戦略を考える上で思いついたトピックを書き出してみる。

   - Oilの将来
   - 為替は米国債利回り低下や景気刺激対策で大量のドルが市場に流れると普通ドル安傾向になると思われるが、ドル建て負債返済によるドル買いとのバランスはどうなっていくのか。
   - 株式市場は方向性が見えないから、オプションのIVから利益を得ることができるか。
   - この先の下落相場に備えて手持ちのETFとかは一旦cash outしたほうがいいのか?
   - 稼ぐには、とどのつまりはEdgeをどうやって見つけるか。risk:rewardをどうするか。(optionsの本は1:10って書いてあったけどそんな大きなgap必要?)
   - 今までmarketをmonitorしてきた経験から何かedgeとなるべきpatternを見つけられないか?
   - positive factors
     - more good neews on covid-19
     - Fed's infinite QE
   - negative factors
     - bad earnings reports
     - wave of bankrupt coming
     - interest rate being 0%
   - who is driving market?
     - AI?
     - market maker?
   - anything for long term investment?
     - dividend focused
   - unemployment rate (monthly) and initial unemployment insurance claims (weekly).
     - 従業員はCARES Actである程度救済されるけど、経営者は?
     - セクタごとに会社の倒産率、自己資本比率などを調べることによりセクタの将来を予測できないか
